// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    application: '0c7dccc6-810a-489a-9675-30a112d03cb8',
    secret: 'dd52b356-a41c-4a7f-b268-07b7b742c05a',
    hostname: 'sandbox.api.moj.io',
    version: 'v1',
    port: '80'
  };

}).call(this);

/*
//@ sourceMappingURL=mojio-config.map
*/
