// Generated by CoffeeScript 1.9.3
(function() {
  var app, authorization_uri, client_id, client_secret, express, oauth2;

  express = require('express');

  app = express();

  client_id = '5f81657f-47f6-4d86-8213-5c01c1f3a243';

  client_secret = 'fcca6c06-3d30-488e-947b-a6291e39ff3c';

  oauth2 = require('simple-oauth2')({
    clientID: client_id,
    clientSecret: client_secret,
    site: 'https://staging-accounts.moj.io',
    tokenPath: '/oauth2/token',
    authorizationPath: '/oauth2/authorize'
  });

  authorization_uri = oauth2.authCode.authorizeURL({
    redirect_uri: 'http://localhost:3000/callback',
    scope: 'full'
  });

  app.get('/auth', function(req, res) {
    return res.redirect(authorization_uri);
  });

  app.get('/callback', function(req, res) {
    var code, saveToken;
    code = req.query.code;
    console.log('/callback');
    saveToken = function(error, result) {
      var token;
      if (error) {
        console.log('Access Token Error', error.message);
      }
      token = oauth2.accessToken.create(result);
      return console.log("Token:" + JSON.stringify(token));
    };
    return oauth2.authCode.getToken({
      client_id: client_id,
      client_secret: client_secret,
      code: code,
      redirect_uri: 'http://localhost:3000/callback'
    }, saveToken);
  });

  app.get('/', function(req, res) {
    return res.send('Hello<br><a href="/auth">Log in with Mojio</a>');
  });

  app.listen(3000);

  console.log('Express server started on port 3000');

}).call(this);

//# sourceMappingURL=authorization_code_flow_simple_oauth.js.map
