// Generated by CoffeeScript 1.9.3
(function() {
  var client_id, client_secret, redirect_uri, sdk;

  client_id = '5f81657f-47f6-4d86-8213-5c01c1f3a243';

  client_secret = 'fcca6c06-3d30-488e-947b-a6291e39ff3c';

  redirect_uri = 'http://localhost:63342/mojio-js-sdk/test/auth/authorize.html';

  sdk = new MojioSDK({
    client_id: client_id,
    client_secret: client_secret,
    site: 'https://staging-accounts.moj.io',
    tokenPath: '/oauth2/token',
    authorizationPath: '/oauth2/authorize',
    test: true
  });

  sdk.token().parse(document, redirect_uri).callback(function(error, result) {
    var div, token;
    if (error) {
      return console.log('Access Token Error', JSON.stringify(error.content) + "  message:" + error.statusMessage + "  url:" + sdk.url());
    } else {
      if (result === "" || (result == null)) {
        if (confirm("Authorize Redirect, token could not be retrieved, you are logged out. Try again?")) {
          return sdk.authorize(redirect_uri).scope(['full']).redirect({
            redirect: function(url) {
              return window.location = url;
            }
          });
        }
      } else {
        token = result;
        console.log("Token:" + JSON.stringify(token));
        alert("Authorization Successful.");
        div = document.getElementById('result');
        div.innerHTML += 'POST /login<br>';
        div.innerHTML += JSON.stringify(result);
        div.innerHTML += "<br>Authorization Successful.<br>";
        if (confirm('You are logged in, logout and try again?')) {
          return sdk.unauthorize(redirect_uri).login().consent().redirect({
            redirect: function(url) {
              return window.location = url;
            }
          });
        }
      }
    }
  });

}).call(this);

//# sourceMappingURL=authorization_implicit_flow.js.map
