// Generated by CoffeeScript 1.6.3
(function() {
  var Mojio, assert, config, mojio, should, testdata;

  Mojio = require('../dist/nodejs/Mojio');

  config = require('../config/mojio-config.coffee');

  mojio = new Mojio(config);

  assert = require("assert");

  testdata = require('./data/mojio-test-data');

  should = require('should');

  describe('Get_CRUD', function() {
    return it('can get resource', function(done) {
      return mojio.login(testdata.username, testdata.password, function(error, result) {
        (error === null).should.be["true"];
        mojio.should.be.an.instanceOf(Mojio);
        mojio.token.should.be.ok;
        result.should.be.an.instanceOf(Object);
        result._id.should.be.an.instanceOf(String);
        return mojio.request({
          resource: 'Apps',
          method: 'GET',
          id: '9189327498-981723498-123948-12342134',
          parameters: {}
        }, function(error, result) {
          (error === null).should.be["true"];
          result.should.be.an.instanceOf(Object);
          return done;
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=crud_test.map
*/
