// Generated by CoffeeScript 1.9.3
(function() {
  var Event, MojioClient, assert, config, mojio_client, should, testObject, testdata;

  MojioClient = require('../lib/nodejs/MojioClient');

  Event = require('../lib/models/Event');

  config = require('./config/mojio-config.coffee');

  mojio_client = new MojioClient(config);

  assert = require('assert');

  testdata = require('./data/mojio-test-data');

  should = require('should');

  testObject = null;

  describe('Event', function() {
    before(function(done) {
      return mojio_client.login(testdata.username, testdata.password, function(error, result) {
        (error === null).should.be["true"];
        return done();
      });
    });
    it('can get Events from Model', function(done) {
      var event;
      event = new Event({});
      event.authorization(mojio_client);
      return event.query({}, function(error, result) {
        var i, instance, len, ref;
        (error === null).should.be["true"];
        mojio_client.should.be.an.instanceOf(MojioClient);
        result.Objects.should.be.an.instanceOf(Array);
        if ((result.Objects != null) && result.Objects instanceof Array) {
          ref = result.Objects;
          for (i = 0, len = ref.length; i < len; i++) {
            instance = ref[i];
            instance.should.be.an.instanceOf(Event);
          }
          testObject = instance;
        } else {
          result.should.be.an.instanceOf(Event);
          testObject = result;
        }
        return done();
      });
    });
    return it('can get Events', function(done) {
      return mojio_client.query(Event, {}, function(error, result) {
        var i, instance, len, ref;
        (error === null).should.be["true"];
        mojio_client.should.be.an.instanceOf(MojioClient);
        result.Objects.should.be.an.instanceOf(Array);
        ref = result.Objects;
        for (i = 0, len = ref.length; i < len; i++) {
          instance = ref[i];
          instance.should.be.an.instanceOf(Event);
        }
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=Event_test.js.map
