// Generated by CoffeeScript 1.6.3
(function() {
  var Mojio, assert, config, mojio, should, testdata;

  Mojio = require('../lib/Mojio');

  config = require('./config/mojio-config.coffee');

  mojio = new Mojio(config);

  assert = require("assert");

  testdata = require('./data/mojio-test-data');

  should = require('should');

  describe('Event', function() {
    return it('can get events', function(done) {
      return mojio.login(testdata.username, testdata.password, function(error, result) {
        (error === null).should.be["true"];
        mojio.should.be.an.instanceOf(Mojio);
        mojio.token.should.be.ok;
        result.should.be.an.instanceOf(Object);
        result._id.should.be.an.instanceOf(String);
        return mojio.events(function(error, result) {
          (error === null).should.be["true"];
          mojio.should.be.an.instanceOf(Mojio);
          return done();
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=events_test.map
*/
