// Generated by CoffeeScript 1.8.0
(function() {
  var App, MojioClient, Observer, app1, app2, assert, config, count, mojio_client, observer, should, testdata;

  MojioClient = require('../lib/nodejs/MojioClient');

  Observer = require('../lib/models/Observer');

  App = require('../lib/models/App');

  config = require('./config/mojio-config.coffee');

  mojio_client = new MojioClient(config);

  assert = require('assert');

  testdata = require('./data/mojio-test-data');

  should = require('should');

  count = [0, 0];

  app1 = null;

  app2 = null;

  observer = null;

  describe('Observer', function() {
    before(function(done) {
      return mojio_client.login(testdata.username, testdata.password, function(error, result) {
        (error === null).should.be["true"];
        return done();
      });
    });
    return it('can Store, Get and Delete Data on Object', function(done) {
      var app;
      console.log("Testing Storage");
      app = new App().mock();
      return mojio_client.post(app, function(error, result) {
        (error === null).should.be["true"];
        app = new App(result);
        return mojio_client.store(app, 'test_key', 'test_value', function(error, result) {
          (error === null).should.be["true"];
          result.result.should.equal("ok");
          return mojio_client.storage(app, 'test_key', function(error, result) {
            (error === null).should.be["true"];
            result.should.equal('test_value');
            return mojio_client.unstore(app, 'test_key', function(error, result) {
              (error === null).should.be["true"];
              return mojio_client.storage(app, 'test_key', function(error, result) {
                (error === null).should.be["false"];
                return mojio_client["delete"](app, function(error, result) {
                  (error === null).should.be["true"];
                  return done();
                });
              });
            });
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=storage_test.js.map
