// Generated by CoffeeScript 1.8.0
(function() {
  var MojioClient, User, assert, config, mojio_client, should, testObject, testdata;

  MojioClient = require('../lib/nodejs/MojioClient');

  User = require('../lib/models/User');

  config = require('./config/mojio-config.coffee');

  mojio_client = new MojioClient(config);

  assert = require('assert');

  testdata = require('./data/mojio-test-data');

  should = require('should');

  testObject = null;

  describe('User', function() {
    before(function(done) {
      return mojio_client.login(testdata.username, testdata.password, function(error, result) {
        (error === null).should.be["true"];
        return done();
      });
    });
    return it('can query Users by UserName', function(done) {
      return mojio_client.query(User, {
        criteria: {
          UserName: 'anonymous'
        },
        limit: 10
      }, function(error, result) {
        var instance, _i, _len, _ref;
        (error === null).should.be["true"];
        mojio_client.should.be.an.instanceOf(MojioClient);
        result.Objects.should.be.an.instanceOf(Array);
        _ref = result.Objects;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          instance = _ref[_i];
          instance.should.be.an.instanceOf(User);
          instance.UserName.should.equal("anonymous");
        }
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=users_test.js.map
