// Generated by CoffeeScript 1.8.0
(function() {
  var App, MojioClient, config, mojio_client;

  MojioClient = this.MojioClient;

  config = {
    application: 'f201b929-d28c-415d-9b71-8112532301cb',
    hostname: 'api.moj.io',
    version: 'v1',
    port: '443',
    scheme: 'https',
    redirect_uri: 'http://localhost:63342/mojio-js/example/authorize.html'
  };

  mojio_client = new MojioClient(config);

  App = mojio_client.model('App');

  $(function() {
    var div;
    if (config.application === 'Your-Sandbox-Application-Key-Here') {
      div = document.getElementById('result');
      div.innerHTML += 'Mojio Error:: Set your application and secret keys in authorize.js.  <br>';
      return;
    }
    return mojio_client.token(function(error, result) {
      if (error) {
        return alert("Authorize Redirect, token could not be retreived:" + error);
      } else {
        alert("Authorization Successful.");
        div = document.getElementById('result');
        div.innerHTML += 'POST /login<br>';
        div.innerHTML += JSON.stringify(result);
        return mojio_client.query(App, {}, function(error, result) {
          var app, apps;
          if (error) {
            div = document.getElementById('result2');
            return div.innerHTML += 'Get Apps Error' + error + '<br>';
          } else {
            apps = mojio_client.getResults(App, result);
            app = apps[0];
            div = document.getElementById('result2');
            div.innerHTML += 'Query /App<br>';
            div.innerHTML += JSON.stringify(result);
            alert("Hit Ok to log out and return to the authorization page.");
            return mojio_client.unauthorize(config.redirect_uri);
          }
        });
      }
    });
  });

}).call(this);

//# sourceMappingURL=authorize_complete.js.map
