// Generated by CoffeeScript 1.9.3
(function() {
  var HttpNodeWrapper;

  module.exports = HttpNodeWrapper = (function() {
    function HttpNodeWrapper() {}

    HttpNodeWrapper.prototype.request = function(request, callback) {
      throw new Error("Not implemented");
    };

    HttpNodeWrapper.prototype.redirect = function(params, callback) {
      throw new Error("Not implemented");
    };

    return HttpNodeWrapper;

  })();

}).call(this);

//# sourceMappingURL=iHttpWrapper.js.map
