// Generated by CoffeeScript 1.9.3
(function() {
  var MojioAsyncAwaitStyle, async, await;

  async = require('asyncawait/async');

  await = require('asyncawait/await');

  module.exports = MojioAsyncAwaitStyle = (function() {
    function MojioAsyncAwaitStyle() {}

    MojioAsyncAwaitStyle.prototype.async = async(function() {
      return await(this.state.initiate(function(error, result) {
        if (result != null) {
          return result;
        }
        if (error != null) {
          return error;
        }
      }));
    });

    return MojioAsyncAwaitStyle;

  })();

}).call(this);
