// Generated by CoffeeScript 1.9.3
(function() {
  var MojioReactiveStyle, Rx;

  Rx = require('rx');

  module.exports = MojioReactiveStyle = (function() {
    function MojioReactiveStyle() {}

    MojioReactiveStyle.prototype.observable = function() {
      var observable, stream;
      stream = Rx.Observable.fromCallback(this.state.initiate);
      observable = stream();
      return observable;
    };

    MojioReactiveStyle.prototype.subscribe = function(result, error, complete) {
      var observable, observer;
      observable = this.observable();
      observer = Rx.Observer.create(result, error, complete);
      return observable.subscribe(observer);
    };

    return MojioReactiveStyle;

  })();

}).call(this);

//# sourceMappingURL=MojioReactiveStyle.js.map
