// Generated by CoffeeScript 1.9.3
(function() {
  var iObservable;

  module.exports = iObservable = (function() {
    function iObservable() {
      throw new Error("Not implemented");
    }

    iObservable.prototype.next = function(value) {
      throw new Error("Not implemented");
    };

    iObservable.prototype.error = function(value) {
      throw new Error("Not implemented");
    };

    iObservable.prototype.done = function(value) {
      throw new Error("Not implemented");
    };

    return iObservable;

  })();

}).call(this);

//# sourceMappingURL=iObserver.js.map
