// Generated by CoffeeScript 1.6.3
(function() {
  var Http, MojioClient;

  Http = require('./HttpNodeWrapper');

  module.exports = MojioClient = (function() {
    var App, Event, Mojio, Product, Subscription, Trip, User, Vehicle, defaults, mojio_models;

    defaults = {
      hostname: 'sandbox.api.moj.io',
      port: '80',
      version: 'v1'
    };

    function MojioClient(options) {
      var _base, _base1, _base2;
      this.options = options;
      if (this.options == null) {
        this.options = {
          hostname: defaults.hostname,
          port: this.defaults.port,
          version: this.defaults.version
        };
      }
      if ((_base = this.options).hostname == null) {
        _base.hostname = defaults.hostname;
      }
      if ((_base1 = this.options).port == null) {
        _base1.port = defaults.port;
      }
      if ((_base2 = this.options).version == null) {
        _base2.version = defaults.version;
      }
      this.options.application = this.options.application;
      this.options.secret = this.options.secret;
      this.options.observerTransport = 'SingalR';
      this.conn = null;
      this.hub = null;
      this.connStatus = null;
      this.token = null;
    }

    /*
        Helpers
    */


    MojioClient._makeParameters = function(params) {
      var property, query, value;
      if (params.length === 0) {
        '';
      }
      query = '?';
      for (property in params) {
        value = params[property];
        query += "" + property + "=" + value + "&";
      }
      return query.slice(0, -1);
    };

    MojioClient.prototype.request = function(request, callback) {
      var http, parts;
      parts = {
        hostname: this.options.hostname,
        host: this.options.hostname,
        port: this.options.port,
        path: '/' + this.options.version,
        method: request.method,
        withCredentials: false
      };
      if ((request.resource != null)) {
        parts.path += '/' + request.resource;
      }
      if ((request.id != null) && request.id !== '') {
        parts.path += '/' + request.id;
      }
      if ((request.parameters != null) && Object.keys(request.parameters).length > 0) {
        parts.path += MojioClient._makeParameters(request.parameters);
      }
      parts.headers = {};
      parts.headers["MojioAPIToken"] = this.getTokenId();
      if ((request.headers != null)) {
        parts.headers += request.headers;
      }
      parts.headers["Content-Type"] = 'application/json';
      if (request.body != null) {
        parts.body = request.body;
      }
      http = new Http();
      return http.request(parts, callback);
    };

    /*
        Login
    */


    MojioClient.prototype.login_resource = 'Login';

    MojioClient.prototype._login = function(username, password, callback) {
      return this.request({
        method: 'POST',
        resource: this.login_resource,
        id: this.options.application,
        parameters: {
          userOrEmail: username,
          password: password,
          secretKey: this.options.secret
        }
      }, callback);
    };

    MojioClient.prototype.login = function(username, password, callback) {
      var _this = this;
      return this._login(username, password, function(error, result) {
        if ((result != null)) {
          _this.token = result;
        }
        return callback(error, result);
      });
    };

    MojioClient.prototype._logout = function(callback) {
      return this.request({
        method: 'DELETE',
        resource: this.login_resource,
        id: typeof mojio_token !== "undefined" && mojio_token !== null ? mojio_token : this.getTokenId()
      }, callback);
    };

    MojioClient.prototype.logout = function(callback) {
      var _this = this;
      return this._logout(function(error, result) {
        _this.token = null;
        return callback(error, result);
      });
    };

    mojio_models = {};

    App = require('../models/App');

    mojio_models['App'] = App;

    Mojio = require('../models/Mojio');

    mojio_models['Mojio'] = Mojio;

    Trip = require('../models/Trip');

    mojio_models['Trip'] = Trip;

    User = require('../models/User');

    mojio_models['User'] = User;

    Vehicle = require('../models/Vehicle');

    mojio_models['Vehicle'] = Vehicle;

    Product = require('../models/Product');

    mojio_models['Product'] = Product;

    Subscription = require('../models/Subscription');

    mojio_models['Subscription'] = Subscription;

    Event = require('../models/Event');

    mojio_models['Event'] = Event;

    MojioClient.prototype.make_model = function(type, json) {
      var data, object, _i, _len, _ref;
      if (json.Data instanceof Array) {
        object = new Array();
        _ref = json.Data;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          data = _ref[_i];
          object.push(new mojio_models[type](data));
        }
      } else if ((json.Data != null)) {
        object = new mojio_models[type](json.Data);
      } else {
        object = new mojio_models[type](json);
      }
      object._client = this;
      return object;
    };

    MojioClient.prototype.query = function(model, criteria, callback) {
      var _this = this;
      if (criteria instanceof Object) {
        return this.request({
          method: 'GET',
          resource: model.resource(),
          parameters: criteria
        }, function(error, result) {
          return callback(error, _this.make_model(model.model(), result));
        });
      } else if (typeof criteria === "string") {
        return this.request({
          method: 'GET',
          resource: model.resource(),
          parameters: {
            id: criteria
          }
        }, function(error, result) {
          return callback(error, _this.make_model(model.model(), result));
        });
      } else {
        return callback("criteria given is not in understood format, string or object.", null);
      }
    };

    MojioClient.prototype.get = function(model, criteria, callback) {
      return this.query(model, criteria, callback);
    };

    MojioClient.prototype.save = function(model, callback) {
      return this.request({
        method: 'PUT',
        resource: model.resource(),
        body: model.stringify(),
        parameters: {
          id: model._id
        }
      }, callback);
    };

    MojioClient.prototype.put = function(model, callback) {
      return this.save(model, callback);
    };

    MojioClient.prototype.create = function(model, callback) {
      return this.request({
        method: 'POST',
        resource: model.resource(),
        body: model.stringify()
      }, callback);
    };

    MojioClient.prototype.post = function(model, callback) {
      return this.create(model, callback);
    };

    MojioClient.prototype["delete"] = function(model, callback) {
      return this.request({
        method: 'DELETE',
        resource: model.resource(),
        parameters: {
          id: model._id
        }
      }, callback);
    };

    MojioClient.prototype.observeEvent = function(id, callback) {
      return this.request({
        method: 'PUT',
        resource: 'Observer',
        parameters: {
          Subject: 'Events',
          SubjectId: id
        }
      }, callback);
    };

    MojioClient.prototype.unobserveEvent = function(id, callback) {
      return this.request({
        method: 'DELETE',
        resource: 'Observer',
        parameters: {
          Subject: 'Events',
          SubjectId: id
        }
      }, callback);
    };

    MojioClient.prototype.validateEntityDescriptor = function(entities, callback) {
      if ((entities != null) && entities(typeof Array)) {
        return callback(null, entities);
      } else if ((entities != null) && entities(type in Object)) {
        return callback(null, [entities]);
      } else {
        return callback("Entity must be an objects specifying a type and a guid id: { type: string id: string } or an array of objects.", null);
      }
    };

    MojioClient.prototype._observe = function(entity, callback) {};

    MojioClient.prototype._unobserve = function(entity, callback) {};

    MojioClient.prototype._unobserveAll = function() {};

    MojioClient.prototype.observe = function(entityDescriptor, callback) {
      return this.validateEntityDescriptor(entityDescriptor, function(error, entities) {
        var entity, observers, _i, _len;
        if (error != null) {
          return;
        }
        observers = [];
        for (_i = 0, _len = entities.length; _i < _len; _i++) {
          entity = entities[_i];
          this.observe(entity, function(error, result) {
            return observers.push(result);
          });
        }
        return callback(null, "Subscribed");
      });
    };

    MojioClient.prototype.unobserve = function(entityDescriptor, callback) {
      if (!(entityDescriptor != null)) {
        this.unobserveAll();
        return callback(null, "Un-Subscribed");
      } else {
        return this.validateEntityDescriptor(entityDescriptor, function(error, entities) {
          var entity, _i, _len;
          if (error != null) {
            callback(error, null);
          }
          for (_i = 0, _len = entities.length; _i < _len; _i++) {
            entity = entities[_i];
            this.unobserve(entity);
          }
          return callback(null, "Un-Subscribed");
        });
      }
    };

    /*
            Schema
    */


    MojioClient.prototype.schema_resource = 'Schema';

    MojioClient.prototype._schema = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.schema_resource
      }, callback);
    };

    MojioClient.prototype.schema = function(callback) {
      var _this = this;
      return this._schema(function(error, result) {
        return callback(error, result);
      });
    };

    /*
            Observer
    */


    MojioClient.prototype.observer_resource = 'Observe';

    MojioClient.prototype._observer = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.observer_resource
      }, callback);
    };

    MojioClient.prototype.observer = function(callback) {
      var _this = this;
      return this._observer(function(error, result) {
        return callback(error, result);
      });
    };

    /*
        Signal R
    */


    MojioClient.prototype.getTokenId = function() {
      if (this.token != null) {
        return this.token._id;
      } else {
        return null;
      }
    };

    MojioClient.prototype.getUserId = function() {
      if (this.token != null) {
        return this.token.UserId;
      } else {
        return null;
      }
    };

    MojioClient.prototype.isLoggedIn = function() {
      return getUserId() !== null;
    };

    MojioClient.prototype.getCurrentUser = function(func) {
      if ((this.user != null)) {
        func(this.user);
      } else if (isLoggedIn()) {
        get('users', getUserId()).done(function(user) {
          if (!(user != null)) {
            return;
          }
          if (getUserId() === this.user._id) {
            this.user = user;
          }
          return func(this.user);
        });
      } else {
        return false;
      }
      return true;
    };

    MojioClient.prototype.dataByMethod = function(data, method) {
      switch (method.toUpperCase()) {
        case 'POST':
        case 'PUT':
          return JSON.stringify(data);
        default:
          return data;
      }
    };

    MojioClient.prototype.getHub = function() {
      if ((this.hub != null)) {
        return this.hub;
      }
      this.conn = $.hubConnection(settings.url + "/signalr", {
        useDefaultPath: false
      });
      this.hub = _conn.createHubProxy('hub');
      this.hub.on("error", function(data) {
        return log(data);
      });
      this.connStatus = this.conn.start().done(function() {
        return this.connStatus = null;
      });
      return this.hub;
    };

    MojioClient.prototype.subscribe = function(type, ids, groups) {
      var action, hub, _ref;
      hub = getHub();
      if (!groups) {
        groups = Mojio.EventTypes;
      }
      if (hub.connection.state !== 1) {
        if (this.connStatus) {
          this.connStatus.done(function() {
            return subscribe(type, ids, groups);
          });
        } else {
          this.connStatus = hub.connection.start().done(function() {
            return subscribe(type, ids, groups);
          });
        }
        return this.connStatus;
      }
      action = (_ref = ids instanceof Array) != null ? _ref : {
        "Subscribe": "SubscribeOne"
      };
      return hub.invoke(action, this.getTokenId(), type, ids, groups);
    };

    MojioClient.prototype.unsubscribe = function(type, ids, groups) {
      var hub;
      hub = getHub();
      if (!groups) {
        groups = Mojio.EventTypes;
      }
      if (hub.connection.state !== 1) {
        if (this.connStatus) {
          this.connStatus.done(function() {
            return unsubscribe(type, ids, groups);
          });
        } else {
          this.connStatus = hub.connection.start().done(function() {
            return unsubscribe(type, ids, groups);
          });
        }
        return this.connStatus;
      }
      return hub.invoke("Unsubscribe", this.getTokenId(), type, ids, groups);
    };

    return MojioClient;

  })();

}).call(this);

/*
//@ sourceMappingURL=MojioClient.map
*/
