// Generated by CoffeeScript 2.0.2
(function() {
  // version 4.0.0
  var FormUrlencoded, Http, MojioGroupingSDK, MojioRestSDK, SignalR, _;

  Http = require('./HttpNodeWrapper');

  SignalR = require('./SignalRNodeWrapper');

  FormUrlencoded = require('form-urlencoded');

  _ = require('underscore');

  MojioRestSDK = require('./MojioRestSDK');

  module.exports = MojioGroupingSDK = class MojioGroupingSDK extends MojioRestSDK {
    constructor(options = {}) {
      super(options);
    }

    // grouping
    group(name, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    add(name, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    remove(name, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    into(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    outof(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

  };

}).call(this);
