// Generated by CoffeeScript 2.0.2
(function() {
  // version 4.0.0
  var FormUrlencoded, Http, MojioGroupingSDK, MojioSharingSDK, SignalR, _;

  Http = require('./HttpNodeWrapper');

  SignalR = require('./SignalRNodeWrapper');

  FormUrlencoded = require('form-urlencoded');

  _ = require('underscore');

  MojioGroupingSDK = require('./MojioGroupingSDK');

  module.exports = MojioSharingSDK = class MojioSharingSDK extends MojioGroupingSDK {
    constructor(options = {}) {
      super(options);
    }

    // sharing and access
    share(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    with(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    access(rules, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    revoke(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

    from(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    }

  };

}).call(this);
