// Generated by CoffeeScript 1.9.3
(function() {
  var MojioModelSDK;

  module.exports = MojioModelSDK = (function() {
    function MojioModelSDK() {}

    MojioModelSDK.prototype.users = function(users) {
      this.state.resource = 'Users';
      this.state.object = users;
      return this;
    };

    MojioModelSDK.prototype.user = function(user) {
      this.users([user]);
      return this;
    };

    MojioModelSDK.prototype.vehicles = function(vehicles) {
      this.state.resource = 'Vehicles';
      this.state.object = vehicles;
      return this;
    };

    MojioModelSDK.prototype.vehicle = function(vehicle) {
      this.vehicles([vehicle]);
      return this;
    };

    MojioModelSDK.prototype.mojios = function(mojios) {
      this.state.resource = 'Vehicles';
      this.state.object = vehicles;
      return this;
    };

    MojioModelSDK.prototype.mojio = function(mojio) {
      this.mojios([mojio]);
      return this;
    };

    MojioModelSDK.prototype.trips = function(trips) {
      this.state.resource = 'Trips';
      this.state.object = trips;
      return this;
    };

    MojioModelSDK.prototype.groups = function(names, callback) {
      this.state.resource = 'Groups';
      this.state.object = names;
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioModelSDK.prototype.group = function(name, callback) {
      this.groups([name]);
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioModelSDK.prototype.permissions = function(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioModelSDK.prototype.image = function(image) {
      this.state.action = 'Image';
      this.state.object = image;
      return this;
    };

    MojioModelSDK.prototype.tags = function(tags) {
      this.state.action = 'Tags';
      this.state.object = tags;
      return this;
    };

    MojioModelSDK.prototype.tag = function(tag) {
      tags([tag]);
      return this;
    };

    MojioModelSDK.prototype.name = function(type) {
      if (type == null) {
        type = "resource";
      }
      return state[type];
    };

    MojioModelSDK.prototype.mock = function() {
      return this;
    };

    return MojioModelSDK;

  })();

}).call(this);

//# sourceMappingURL=MojioModelSDK.js.map
