// Generated by CoffeeScript 1.6.3
(function() {
  var HttpBrowser;

  module.exports = HttpBrowser = (function() {
    var dataByMethod, sendRequest;

    function HttpBrowser($) {
      this.$ = $;
    }

    dataByMethod = function(data, method) {
      switch (method.toUpperCase()) {
        case 'POST':
        case 'PUT':
          return JSON.stringify(data);
        default:
          return data;
      }
    };

    sendRequest = function(url, data, method) {
      var headers;
      if (!method) {
        method = "GET";
      }
      if (!data) {
        data = {};
      }
      headers = {};
      return this.$.ajax(url, {
        data: dataByMethod(data, method),
        headers: headers,
        contentType: "application/json",
        type: method,
        cache: false,
        error: function(obj, status, error) {
          return log('Error during request: (' + status + ') ' + error);
        }
      });
    };

    HttpBrowser.prototype.request = function(params, callback) {
      var url;
      if (params.method == null) {
        params.method = "GET";
      }
      if ((params.host == null) && (params.hostname != null)) {
        params.host = params.hostname;
      }
      if (params.scheme == null) {
        params.scheme = window.location.protocol.split(':')[0];
      }
      if (params.data == null) {
        params.data = {};
      }
      url = params.scheme + "://" + params.host + ":" + params.port + params.path;
      return sendRequest(url, params.data, params.method).done(function(result) {
        return callback(null, result);
      }).fail(function() {
        return callback("Failed", null);
      });
    };

    return HttpBrowser;

  })();

}).call(this);

/*
//@ sourceMappingURL=HttpBrowser.map
*/
