// Generated by CoffeeScript 1.8.0
(function() {
  var AccelerometerObserver, MojioModel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = AccelerometerObserver = (function(_super) {
    __extends(AccelerometerObserver, _super);

    AccelerometerObserver.prototype._schema = {
      "AccelerometerLow": {
        "X": "Float",
        "Y": "Float",
        "Z": "Float"
      },
      "AccelerometerHigh": {
        "X": "Float",
        "Y": "Float",
        "Z": "Float"
      },
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "Tokens": "Array",
      "_id": "String",
      "_deleted": "Boolean"
    };

    AccelerometerObserver.prototype._resource = 'AccelerometerObservers';

    AccelerometerObserver.prototype._model = 'AccelerometerObserver';

    function AccelerometerObserver(json) {
      AccelerometerObserver.__super__.constructor.call(this, json);
    }

    AccelerometerObserver._resource = 'AccelerometerObservers';

    AccelerometerObserver._model = 'AccelerometerObserver';

    AccelerometerObserver.resource = function() {
      return AccelerometerObserver._resource;
    };

    AccelerometerObserver.model = function() {
      return AccelerometerObserver._model;
    };

    return AccelerometerObserver;

  })(MojioModel);

}).call(this);
