// Generated by CoffeeScript 2.0.2
(function() {
  var Address, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = Address = (function() {
    class Address extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return Address._resource;
      }

      static model() {
        return Address._model;
      }

    };

    // instance variables
    Address.prototype._schema = {
      "Address1": "String",
      "Address2": "String",
      "City": "String",
      "State": "String",
      "Zip": "String",
      "Country": "String"
    };

    Address.prototype._resource = 'Addresss';

    Address.prototype._model = 'Address';

    // class variables and functions
    Address._resource = 'Addresss';

    Address._model = 'Address';

    return Address;

  })();

}).call(this);
