// Generated by CoffeeScript 2.0.2
(function() {
  var AltitudeObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = AltitudeObserver = (function() {
    class AltitudeObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return AltitudeObserver._resource;
      }

      static model() {
        return AltitudeObserver._model;
      }

    };

    // instance variables
    AltitudeObserver.prototype._schema = {
      "AltitudeLow": "Float",
      "AltitudeHigh": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    AltitudeObserver.prototype._resource = 'AltitudeObservers';

    AltitudeObserver.prototype._model = 'AltitudeObserver';

    // class variables and functions
    AltitudeObserver._resource = 'AltitudeObservers';

    AltitudeObserver._model = 'AltitudeObserver';

    return AltitudeObserver;

  })();

}).call(this);
