// Generated by CoffeeScript 2.0.2
(function() {
  var App, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = App = (function() {
    class App extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return App._resource;
      }

      static model() {
        return App._model;
      }

    };

    // instance variables
    App.prototype._schema = {
      "Type": "String",
      "Name": "String",
      "Description": "String",
      "CreationDate": "String",
      "Downloads": "Integer",
      "RedirectUris": "String",
      "ApplicationType": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    App.prototype._resource = 'Apps';

    App.prototype._model = 'App';

    // class variables and functions
    App._resource = 'Apps';

    App._model = 'App';

    return App;

  })();

}).call(this);
