// Generated by CoffeeScript 2.0.2
(function() {
  var BatteryVoltageObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = BatteryVoltageObserver = (function() {
    class BatteryVoltageObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return BatteryVoltageObserver._resource;
      }

      static model() {
        return BatteryVoltageObserver._model;
      }

    };

    // instance variables
    BatteryVoltageObserver.prototype._schema = {
      "BatteryVoltageLow": "Float",
      "BatteryVoltageHigh": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    BatteryVoltageObserver.prototype._resource = 'BatteryVoltageObservers';

    BatteryVoltageObserver.prototype._model = 'BatteryVoltageObserver';

    // class variables and functions
    BatteryVoltageObserver._resource = 'BatteryVoltageObservers';

    BatteryVoltageObserver._model = 'BatteryVoltageObserver';

    return BatteryVoltageObserver;

  })();

}).call(this);
