// Generated by CoffeeScript 2.0.2
(function() {
  var ConditionalObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = ConditionalObserver = (function() {
    class ConditionalObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return ConditionalObserver._resource;
      }

      static model() {
        return ConditionalObserver._model;
      }

    };

    // instance variables
    ConditionalObserver.prototype._schema = {
      "Field": "String",
      "Threshold1": "Float",
      "Threshold2": "Float",
      "Operator1": "String",
      "Operator2": "String",
      "Conjunction": "String",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    ConditionalObserver.prototype._resource = 'ConditionalObservers';

    ConditionalObserver.prototype._model = 'ConditionalObserver';

    // class variables and functions
    ConditionalObserver._resource = 'ConditionalObservers';

    ConditionalObserver._model = 'ConditionalObserver';

    return ConditionalObserver;

  })();

}).call(this);
