// Generated by CoffeeScript 2.0.2
(function() {
  var DiagnosticCodeObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = DiagnosticCodeObserver = (function() {
    class DiagnosticCodeObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return DiagnosticCodeObserver._resource;
      }

      static model() {
        return DiagnosticCodeObserver._model;
      }

    };

    // instance variables
    DiagnosticCodeObserver.prototype._schema = {
      "DiagnosticCodes": "Array",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    DiagnosticCodeObserver.prototype._resource = 'DiagnosticCodeObservers';

    DiagnosticCodeObserver.prototype._model = 'DiagnosticCodeObserver';

    // class variables and functions
    DiagnosticCodeObserver._resource = 'DiagnosticCodeObservers';

    DiagnosticCodeObserver._model = 'DiagnosticCodeObserver';

    return DiagnosticCodeObserver;

  })();

}).call(this);
