// Generated by CoffeeScript 1.8.0
(function() {
  var DiagnosticCodeObserver, MojioModel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = DiagnosticCodeObserver = (function(_super) {
    __extends(DiagnosticCodeObserver, _super);

    DiagnosticCodeObserver.prototype._schema = {
      "DiagnosticCodes": "Array",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    DiagnosticCodeObserver.prototype._resource = 'DiagnosticCodeObservers';

    DiagnosticCodeObserver.prototype._model = 'DiagnosticCodeObserver';

    function DiagnosticCodeObserver(json) {
      DiagnosticCodeObserver.__super__.constructor.call(this, json);
    }

    DiagnosticCodeObserver._resource = 'DiagnosticCodeObservers';

    DiagnosticCodeObserver._model = 'DiagnosticCodeObserver';

    DiagnosticCodeObserver.resource = function() {
      return DiagnosticCodeObserver._resource;
    };

    DiagnosticCodeObserver.model = function() {
      return DiagnosticCodeObserver._model;
    };

    return DiagnosticCodeObserver;

  })(MojioModel);

}).call(this);
