// Generated by CoffeeScript 2.0.2
(function() {
  var Event, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = Event = (function() {
    class Event extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return Event._resource;
      }

      static model() {
        return Event._model;
      }

    };

    // instance variables
    Event.prototype._schema = {
      "Type": "Integer",
      "MojioId": "String",
      "VehicleId": "String",
      "OwnerId": "String",
      "EventType": "Integer",
      "Time": "String",
      "Location": {
        "Lat": "Float",
        "Lng": "Float",
        "FromLockedGPS": "Boolean",
        "Dilution": "Float"
      },
      "TimeIsApprox": "Boolean",
      "BatteryVoltage": "Float",
      "ConnectionLost": "Boolean",
      "_id": "String",
      "_deleted": "Boolean",
      "Accelerometer": {
        "X": "Float",
        "Y": "Float",
        "Z": "Float"
      },
      "TripId": "String",
      "Altitude": "Float",
      "Heading": "Float",
      "Distance": "Float",
      "FuelLevel": "Float",
      "FuelEfficiency": "Float",
      "Speed": "Float",
      "Acceleration": "Float",
      "Deceleration": "Float",
      "Odometer": "Float",
      "RPM": "Integer",
      "DTCs": "Array",
      "MilStatus": "Boolean",
      "Force": "Float",
      "MaxSpeed": "Float",
      "AverageSpeed": "Float",
      "MovingTime": "Float",
      "IdleTime": "Float",
      "StopTime": "Float",
      "MaxRPM": "Float",
      "EventTypes": "Array",
      "Timing": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String"
    };

    Event.prototype._resource = 'Events';

    Event.prototype._model = 'Event';

    // class variables and functions
    Event._resource = 'Events';

    Event._model = 'Event';

    return Event;

  })();

}).call(this);
