// Generated by CoffeeScript 2.0.2
(function() {
  var EventObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = EventObserver = (function() {
    class EventObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return EventObserver._resource;
      }

      static model() {
        return EventObserver._model;
      }

    };

    // instance variables
    EventObserver.prototype._schema = {
      "EventTypes": "Array",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    EventObserver.prototype._resource = 'EventObservers';

    EventObserver.prototype._model = 'EventObserver';

    // class variables and functions
    EventObserver._resource = 'EventObservers';

    EventObserver._model = 'EventObserver';

    return EventObserver;

  })();

}).call(this);
