// Generated by CoffeeScript 2.0.2
(function() {
  var FuelLevelObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = FuelLevelObserver = (function() {
    class FuelLevelObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return FuelLevelObserver._resource;
      }

      static model() {
        return FuelLevelObserver._model;
      }

    };

    // instance variables
    FuelLevelObserver.prototype._schema = {
      "FuelLow": "Float",
      "FuelHigh": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    FuelLevelObserver.prototype._resource = 'FuelLevelObservers';

    FuelLevelObserver.prototype._model = 'FuelLevelObserver';

    // class variables and functions
    FuelLevelObserver._resource = 'FuelLevelObservers';

    FuelLevelObserver._model = 'FuelLevelObserver';

    return FuelLevelObserver;

  })();

}).call(this);
