// Generated by CoffeeScript 2.0.2
(function() {
  var GeoFenceObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = GeoFenceObserver = (function() {
    class GeoFenceObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return GeoFenceObserver._resource;
      }

      static model() {
        return GeoFenceObserver._model;
      }

    };

    // instance variables
    GeoFenceObserver.prototype._schema = {
      "Location": {
        "Lat": "Float",
        "Lng": "Float",
        "FromLockedGPS": "Boolean",
        "Dilution": "Float"
      },
      "Radius": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    GeoFenceObserver.prototype._resource = 'GeoFenceObservers';

    GeoFenceObserver.prototype._model = 'GeoFenceObserver';

    // class variables and functions
    GeoFenceObserver._resource = 'GeoFenceObservers';

    GeoFenceObserver._model = 'GeoFenceObserver';

    return GeoFenceObserver;

  })();

}).call(this);
