// Generated by CoffeeScript 2.0.2
(function() {
  var HeadingObserver, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = HeadingObserver = (function() {
    class HeadingObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return HeadingObserver._resource;
      }

      static model() {
        return HeadingObserver._model;
      }

    };

    // instance variables
    HeadingObserver.prototype._schema = {
      "HeadingLow": "Float",
      "HeadingHigh": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    HeadingObserver.prototype._resource = 'HeadingObservers';

    HeadingObserver.prototype._model = 'HeadingObserver';

    // class variables and functions
    HeadingObserver._resource = 'HeadingObservers';

    HeadingObserver._model = 'HeadingObserver';

    return HeadingObserver;

  })();

}).call(this);
