// Generated by CoffeeScript 2.0.2
(function() {
  var Login, MojioModel;

  MojioModel = require('./MojioModel');

  module.exports = Login = (function() {
    class Login extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return Login._resource;
      }

      static model() {
        return Login._model;
      }

    };

    // instance variables
    Login.prototype._schema = {
      "Type": "String",
      "AppId": "String",
      "UserId": "String",
      "ValidUntil": "String",
      "Scopes": "String",
      "Sandboxed": "Boolean",
      "Depricated": "Boolean",
      "_id": "String",
      "_deleted": "Boolean"
    };

    Login.prototype._resource = 'Login';

    Login.prototype._model = 'Login';

    // class variables and functions
    Login._resource = 'Login';

    Login._model = 'Login';

    return Login;

  })();

}).call(this);
