// Generated by CoffeeScript 1.6.3
(function() {
  var Mojio, MojioModel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = Mojio = (function(_super) {
    __extends(Mojio, _super);

    function Mojio(json) {
      this.schema = {
        "Type": "Integer",
        "OwnerId": "String",
        "Name": "String",
        "Imei": "String",
        "LastContactTime": "String",
        "VehicleId": "String",
        "_id": "String",
        "_deleted": "Boolean"
      };
      Mojio.__super__.constructor.call(this, json);
    }

    return Mojio;

  })(MojioModel);

}).call(this);

/*
//@ sourceMappingURL=Mojio.map
*/
