// Generated by CoffeeScript 1.6.3
(function() {
  var MojioModel, Observer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = Observer = (function(_super) {
    __extends(Observer, _super);

    Observer.prototype._schema = {
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "_id": "String",
      "_deleted": "Boolean"
    };

    Observer.prototype._resource = 'Observers';

    Observer.prototype._model = 'Observer';

    function Observer(json) {
      Observer.__super__.constructor.call(this, json);
    }

    Observer.prototype.observe = function(children, callback) {
      if (children == null) {
        children = null;
      }
      return callback(null, null);
    };

    Observer.prototype.storage = function(property, value, callback) {
      return callback(null, null);
    };

    Observer.prototype.statistic = function(expression, callback) {
      return callback(null, null);
    };

    Observer._resource = 'Observers';

    Observer._model = 'Observer';

    Observer.resource = function() {
      return Observer._resource;
    };

    Observer.model = function() {
      return Observer._model;
    };

    return Observer;

  })(MojioModel);

}).call(this);

/*
//@ sourceMappingURL=Observer.map
*/
