// Generated by CoffeeScript 1.6.3
(function() {
  var MojioModel, Observer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = Observer = (function(_super) {
    __extends(Observer, _super);

    function Observer(json) {
      this.schema = {
        "Type": "Integer",
        "Name": "String",
        "ObserverType": "Integer",
        "AppId": "String",
        "OwnerId": "String",
        "Parent": "String",
        "ParentId": "String",
        "Subject": "String",
        "SubjectId": "String",
        "Transports": "Integer",
        "Status": "Integer",
        "Tokens": "Array",
        "_id": "String",
        "_deleted": "Boolean"
      };
      Observer.__super__.constructor.call(this, json);
    }

    return Observer;

  })(MojioModel);

}).call(this);

/*
//@ sourceMappingURL=Observer.map
*/
