// Generated by CoffeeScript 2.0.2
(function() {
  var MojioModel, Product;

  MojioModel = require('./MojioModel');

  module.exports = Product = (function() {
    class Product extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return Product._resource;
      }

      static model() {
        return Product._model;
      }

    };

    // instance variables
    Product.prototype._schema = {
      "Type": "String",
      "AppId": "String",
      "Name": "String",
      "Description": "String",
      "Shipping": "Boolean",
      "Taxable": "Boolean",
      "Price": "Float",
      "Discontinued": "Boolean",
      "OwnerId": "String",
      "CreationDate": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    Product.prototype._resource = 'Products';

    Product.prototype._model = 'Product';

    // class variables and functions
    Product._resource = 'Products';

    Product._model = 'Product';

    return Product;

  })();

}).call(this);
