// Generated by CoffeeScript 2.0.2
(function() {
  var MojioModel, RPMObserver;

  MojioModel = require('./MojioModel');

  module.exports = RPMObserver = (function() {
    class RPMObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return RPMObserver._resource;
      }

      static model() {
        return RPMObserver._model;
      }

    };

    // instance variables
    RPMObserver.prototype._schema = {
      "RpmLow": "Float",
      "RpmHigh": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    RPMObserver.prototype._resource = 'RPMObservers';

    RPMObserver.prototype._model = 'RPMObserver';

    // class variables and functions
    RPMObserver._resource = 'RPMObservers';

    RPMObserver._model = 'RPMObserver';

    return RPMObserver;

  })();

}).call(this);
