// Generated by CoffeeScript 1.8.0
(function() {
  var MojioModel, ScriptObserver,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = ScriptObserver = (function(_super) {
    __extends(ScriptObserver, _super);

    ScriptObserver.prototype._schema = {
      "Script": "String",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    ScriptObserver.prototype._resource = 'ScriptObservers';

    ScriptObserver.prototype._model = 'ScriptObserver';

    function ScriptObserver(json) {
      ScriptObserver.__super__.constructor.call(this, json);
    }

    ScriptObserver._resource = 'ScriptObservers';

    ScriptObserver._model = 'ScriptObserver';

    ScriptObserver.resource = function() {
      return ScriptObserver._resource;
    };

    ScriptObserver.model = function() {
      return ScriptObserver._model;
    };

    return ScriptObserver;

  })(MojioModel);

}).call(this);
