// Generated by CoffeeScript 2.0.2
(function() {
  var MojioModel, SpeedObserver;

  MojioModel = require('./MojioModel');

  module.exports = SpeedObserver = (function() {
    class SpeedObserver extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return SpeedObserver._resource;
      }

      static model() {
        return SpeedObserver._model;
      }

    };

    // instance variables
    SpeedObserver.prototype._schema = {
      "SpeedLow": "Float",
      "SpeedHigh": "Float",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "TimeWindow": "String",
      "BroadcastOnlyRecent": "Boolean",
      "Throttle": "String",
      "NextAllowedBroadcast": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    SpeedObserver.prototype._resource = 'SpeedObservers';

    SpeedObserver.prototype._model = 'SpeedObserver';

    // class variables and functions
    SpeedObserver._resource = 'SpeedObservers';

    SpeedObserver._model = 'SpeedObserver';

    return SpeedObserver;

  })();

}).call(this);
