// Generated by CoffeeScript 1.6.3
(function() {
  var MojioModel, Trip,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = Trip = (function(_super) {
    __extends(Trip, _super);

    function Trip(json) {
      this.schema = {
        "Type": "Integer",
        "MojioId": "String",
        "VehicleId": "String",
        "StartTime": "String",
        "LastUpdatedTime": "String",
        "EndTime": "String",
        "MaxSpeed": "Float",
        "MaxAcceleration": "Float",
        "MaxDeceleration": "Float",
        "MaxRPM": "Integer",
        "FuelLevel": "Float",
        "FuelEfficiency": "Float",
        "Distance": "Float",
        "MovingTime": "Float",
        "IdleTime": "Float",
        "StopTime": "Float",
        "StartLocation": "Object",
        "LastKnownLocation": "Object",
        "EndLocation": "Object",
        "StartAddress": "Object",
        "EndAddress": "Object",
        "ForcefullyEnded": "Boolean",
        "StartMilage": "Float",
        "EndMilage": "Float",
        "_id": "String",
        "_deleted": "Boolean"
      };
      Trip.__super__.constructor.call(this, json);
    }

    return Trip;

  })(MojioModel);

}).call(this);

/*
//@ sourceMappingURL=Trip.map
*/
