// Generated by CoffeeScript 2.0.2
(function() {
  var MojioModel, User;

  MojioModel = require('./MojioModel');

  module.exports = User = (function() {
    class User extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return User._resource;
      }

      static model() {
        return User._model;
      }

    };

    // instance variables
    User.prototype._schema = {
      "Type": "Integer",
      "UserName": "String",
      "FirstName": "String",
      "LastName": "String",
      "Email": "String",
      "UserCount": "Integer",
      "Credits": "Integer",
      "CreationDate": "String",
      "LastActivityDate": "String",
      "LastLoginDate": "String",
      "Locale": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    User.prototype._resource = 'Users';

    User.prototype._model = 'User';

    // class variables and functions
    User._resource = 'Users';

    User._model = 'User';

    return User;

  })();

}).call(this);
