// Generated by CoffeeScript 1.6.3
(function() {
  var MojioModel, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MojioModel = require('./MojioModel');

  module.exports = User = (function(_super) {
    __extends(User, _super);

    function User(json) {
      this.schema = {
        "Type": "Integer",
        "UserName": "String",
        "FirstName": "String",
        "LastName": "String",
        "Email": "String",
        "UserCount": "Integer",
        "Credits": "Integer",
        "CreationDate": "String",
        "LastActivityDate": "String",
        "LastLoginDate": "String",
        "_id": "String",
        "_deleted": "Boolean"
      };
      User.__super__.constructor.call(this, json);
    }

    return User;

  })(MojioModel);

}).call(this);

/*
//@ sourceMappingURL=User.map
*/
