// Generated by CoffeeScript 1.9.3
(function() {
  var MojioModel, User,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MojioModel = require('./MojioModel');

  module.exports = User = (function(superClass) {
    extend(User, superClass);

    User.prototype._schema = {
      "Type": "Integer",
      "UserName": "String",
      "FirstName": "String",
      "LastName": "String",
      "Email": "String",
      "UserCount": "Integer",
      "Credits": "Integer",
      "CreationDate": "String",
      "LastActivityDate": "String",
      "LastLoginDate": "String",
      "Locale": "String",
      "_id": "String",
      "_deleted": "Boolean"
    };

    User.prototype._resource = 'Users';

    User.prototype._model = 'User';

    function User(json) {
      User.__super__.constructor.call(this, json);
    }

    User._resource = 'Users';

    User._model = 'User';

    User.resource = function() {
      return User._resource;
    };

    User.model = function() {
      return User._model;
    };

    return User;

  })(MojioModel);

}).call(this);
