// Generated by CoffeeScript 2.0.2
(function() {
  var MojioModel, Vehicle;

  MojioModel = require('./MojioModel');

  module.exports = Vehicle = (function() {
    class Vehicle extends MojioModel {
      constructor(json) {
        super(json);
      }

      static resource() {
        return Vehicle._resource;
      }

      static model() {
        return Vehicle._model;
      }

    };

    // instance variables
    Vehicle.prototype._schema = {
      "Type": "Integer",
      "OwnerId": "String",
      "MojioId": "String",
      "Name": "String",
      "VIN": "String",
      "LicensePlate": "String",
      "IgnitionOn": "Boolean",
      "VehicleTime": "String",
      "LastTripEvent": "String",
      "LastLocationTime": "String",
      "LastLocation": {
        "Lat": "Float",
        "Lng": "Float",
        "FromLockedGPS": "Boolean",
        "Dilution": "Float"
      },
      "LastSpeed": "Float",
      "FuelLevel": "Float",
      "LastAcceleration": "Float",
      "LastAccelerometer": "Object",
      "LastAltitude": "Float",
      "LastBatteryVoltage": "Float",
      "LastDistance": "Float",
      "LastHeading": "Float",
      "LastVirtualOdometer": "Float",
      "LastOdometer": "Float",
      "LastRpm": "Float",
      "LastFuelEfficiency": "Float",
      "CurrentTrip": "String",
      "LastTrip": "String",
      "LastContactTime": "String",
      "MilStatus": "Boolean",
      "DiagnosticCodes": "Object",
      "FaultsDetected": "Boolean",
      "LastLocationTimes": "Array",
      "LastLocations": "Array",
      "LastSpeeds": "Array",
      "LastHeadings": "Array",
      "LastAltitudes": "Array",
      "Viewers": "Array",
      "_id": "String",
      "_deleted": "Boolean"
    };

    Vehicle.prototype._resource = 'Vehicles';

    Vehicle.prototype._model = 'Vehicle';

    // class variables and functions
    Vehicle._resource = 'Vehicles';

    Vehicle._model = 'Vehicle';

    return Vehicle;

  })();

}).call(this);
