// Generated by CoffeeScript 1.9.3
(function() {
  var MojioModelSDK;

  module.exports = MojioModelSDK = (function() {
    function MojioModelSDK() {}

    MojioModelSDK.prototype.configure = function(options) {
      if (options == null) {
        options = {};
      }
      _.extend(this, options);
      return this;
    };

    MojioModelSDK.prototype.users = function(users) {
      return this;
    };

    MojioModelSDK.prototype.user = function(user) {
      return this;
    };

    MojioModelSDK.prototype.vehicles = function(vehicles) {
      return this;
    };

    MojioModelSDK.prototype.vehicle = function(vehicle) {
      return this;
    };

    MojioModelSDK.prototype.mojios = function(mojios) {
      return this;
    };

    MojioModelSDK.prototype.mojio = function(mojio) {
      return this;
    };

    MojioModelSDK.prototype.trips = function(trips) {
      return this;
    };

    MojioModelSDK.prototype.group = function(name, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioModelSDK.prototype.groups = function(name, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioModelSDK.prototype.permissions = function(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioModelSDK.prototype.image = function(mojios) {
      return this;
    };

    MojioModelSDK.prototype.tags = function(mojio) {
      return this;
    };

    MojioModelSDK.prototype.tag = function(mojio) {
      return this;
    };

    MojioModelSDK.prototype.mock = function() {
      return this;
    };

    return MojioModelSDK;

  })();

}).call(this);

//# sourceMappingURL=MojioModelSDK.js.map
