// Generated by CoffeeScript 1.9.3
(function() {
  var Module, MojioPushSDK, MojioSDK, MojioSDKState, _,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _ = require('underscore');

  MojioSDKState = require('../state/MojioSDKState');

  MojioPushSDK = require('./MojioPushSDK');

  Module = require('../helpers/Module');

  module.exports = MojioSDK = (function(superClass) {
    var defaults;

    extend(MojioSDK, superClass);

    defaults = {
      sdk_env: 'nodejs',
      test: false
    };

    function MojioSDK(options) {
      var i, len, ref, style;
      if (options == null) {
        options = {};
      }
      this.include(options.sdk ? options.sdk : MojioPushSDK);
      if (options.styles) {
        ref = options.styles;
        for (i = 0, len = ref.length; i < len; i++) {
          style = ref[i];
          this.include(style);
        }
      }
      delete options.sdk;
      delete options.styles;
      this.configure(options, defaults);
      this.state = new MojioSDKState(options);
      MojioSDK.__super__.constructor.call(this);
    }

    MojioSDK.prototype.configure = function(options, defaults) {
      if (options == null) {
        options = {};
      }
      if (defaults == null) {
        defaults = {};
      }
      _.extend(this, options);
      _.defaults(this, defaults);
      return this;
    };

    MojioSDK.prototype.sync = function() {
      var result;
      this.state.initiate(function(error, result) {});
      result = true;
      return result;
    };

    MojioSDK.prototype.callback = function(callback) {
      console.log(this.state.url());
      return this.state.initiate(callback);
    };

    MojioSDK.prototype.show = function() {
      return this.state.show();
    };

    return MojioSDK;

  })(Module);

}).call(this);

//# sourceMappingURL=MojioSDK.js.map
