// Generated by CoffeeScript 1.7.1
(function() {
  var Http, HttpNodeWrapper;

  Http = require('http');

  module.exports = HttpNodeWrapper = (function() {
    function HttpNodeWrapper() {}

    HttpNodeWrapper.prototype.request = function(params, callback) {
      var action;
      action = Http.request(params);
      action.on('response', function(response) {
        var data;
        if (response.statusCode > 299) {
          return callback(response, null);
        } else if (response.statusCode !== 204) {
          data = "";
          if (typeof window === "undefined" || window === null) {
            response.setEncoding('utf8');
          }
          response.on('data', function(chunk) {
            return data += chunk;
          });
          return response.on('end', function() {
            if (data instanceof Object) {
              return callback(data, null);
            } else {
              return callback(null, JSON.parse(data));
            }
          });
        } else {
          return callback(null, response);
        }
      });
      action.on('error', function(error) {
        return callback(error, null);
      });
      return action.end();
    };

    return HttpNodeWrapper;

  })();

}).call(this);

//# sourceMappingURL=HttpNodeWrapper.map
