// Generated by CoffeeScript 1.7.1
(function() {
  var Http, MojioClient;

  Http = require('./HttpNodeWrapper');

  module.exports = MojioClient = (function() {
    var defaults;

    defaults = {
      hostname: 'sandbox.api.moj.io',
      port: '80',
      version: 'v1'
    };

    function MojioClient(options) {
      var _base, _base1, _base2;
      this.options = options;
      if (this.options == null) {
        this.options = {
          hostname: defaults.hostname,
          port: this.defaults.port,
          version: this.defaults.version
        };
      }
      if ((_base = this.options).hostname == null) {
        _base.hostname = defaults.hostname;
      }
      if ((_base1 = this.options).port == null) {
        _base1.port = defaults.port;
      }
      if ((_base2 = this.options).version == null) {
        _base2.version = defaults.version;
      }
      this.options.application = this.options.application;
      this.options.secret = this.options.secret;
    }


    /*
        Helpers
     */

    MojioClient.prototype._makeParameters = function(params) {
      var property, query, value;
      if (params.length === 0) {
        '';
      }
      query = '?';
      for (property in params) {
        value = params[property];
        query += "" + property + "=" + value + "&";
      }
      return query.slice(0, -1);
    };

    MojioClient.prototype.request = function(request, callback) {
      var http, parts;
      parts = {
        hostname: this.options.hostname,
        host: this.options.hostname,
        port: this.options.port,
        path: '/' + this.options.version,
        method: request.method,
        withCredentials: false
      };
      if ((request.resource != null)) {
        parts.path += '/' + request.resource;
      }
      if ((request.id != null) && request.id !== '') {
        parts.path += '/' + request.id;
      }
      if ((request.parameters != null) && Object.keys(request.parameters).length > 0) {
        parts.path += this._makeParameters(request.parameters);
      }
      parts.headers = {};
      if (this.token != null) {
        parts.headers["MojioAPIToken"] = this.token;
      }
      if ((request.headers != null)) {
        parts.headers += request.headers;
      }
      if (request.body) {
        parts.body = request.body;
      }
      http = new Http();
      return http.request(parts, callback);
    };


    /*
        Login
     */

    MojioClient.prototype.login_resource = 'Login';

    MojioClient.prototype._login = function(username, password, callback) {
      return this.request({
        method: 'POST',
        resource: this.login_resource,
        id: this.options.application,
        parameters: {
          userOrEmail: username,
          password: password,
          secretKey: this.options.secret
        }
      }, callback);
    };

    MojioClient.prototype.login = function(username, password, callback) {
      return this._login(username, password, (function(_this) {
        return function(error, result) {
          if ((result != null)) {
            _this.token = result._id;
          }
          return callback(error, result);
        };
      })(this));
    };

    MojioClient.prototype._logout = function(callback) {
      return this.request({
        method: 'DELETE',
        resource: this.login_resource,
        id: typeof mojio_token !== "undefined" && mojio_token !== null ? mojio_token : this.token
      }, callback);
    };

    MojioClient.prototype.logout = function(callback) {
      return this._logout((function(_this) {
        return function(error, result) {
          _this.token = null;
          return callback(error, result);
        };
      })(this));
    };


    /*
        CRUD
     */

    MojioClient.prototype.get = function(request, callback) {
      return this.request(request, callback);
    };

    MojioClient.prototype.post = function(request, callback) {
      return this.request(request, callback);
    };

    MojioClient.prototype.put = function(request, callback) {
      return this.request(request, callback);
    };

    MojioClient.prototype["delete"] = function(request, callback) {
      return this.request(request, callback);
    };


    /*
       App
     */

    MojioClient.prototype.apps_resource = 'Apps';

    MojioClient.prototype._apps = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.apps_resource
      }, callback);
    };

    MojioClient.prototype.apps = function(callback) {
      return this._apps((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };


    /*
       Mojio
     */

    MojioClient.prototype.mojios_resource = 'Mojios';

    MojioClient.prototype._mojios = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.mojios_resource
      }, callback);
    };

    MojioClient.prototype.mojios = function(callback) {
      return this._mojios((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };


    /*
       Vehicle
     */

    MojioClient.prototype.vehicles_resource = 'Vehicles';

    MojioClient.prototype._vehicles = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.vehicles_resource
      }, callback);
    };

    MojioClient.prototype.vehicles = function(callback) {
      return this._vehicles((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };


    /*
       User
     */

    MojioClient.prototype.users_resource = 'Users';

    MojioClient.prototype._users = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.users_resource
      }, callback);
    };

    MojioClient.prototype.users = function(callback) {
      return this._users((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };


    /*
       Trip
     */

    MojioClient.prototype.trips_resource = 'Trips';

    MojioClient.prototype._trips = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.trips_resource
      }, callback);
    };

    MojioClient.prototype.trips = function(callback) {
      return this._trips((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };


    /*
       Event
     */

    MojioClient.prototype.events_resource = 'Events';

    MojioClient.prototype._events = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.events_resource
      }, callback);
    };

    MojioClient.prototype.events = function(callback) {
      return this._events((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };


    /*
            Schema
     */

    MojioClient.prototype.schema_resource = 'Schema';

    MojioClient.prototype._schema = function(callback) {
      return this.request({
        method: 'GET',
        resource: this.schema_resource
      }, callback);
    };

    MojioClient.prototype.schema = function(callback) {
      return this._schema((function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };

    return MojioClient;

  })();

}).call(this);

//# sourceMappingURL=MojioClient.map
