// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    application: 'CB154FCC-4EC1-4EBB-A703-3A8C6E8A9525',
    secret: '78D310D5-A23F-4F05-A0E5-35696AAA9764',
    hostname: 'staging.api.moj.io',
    version: 'v1',
    port: '80'
  };

}).call(this);

/*
//@ sourceMappingURL=mojio-config.map
*/
