// Generated by CoffeeScript 1.9.3
(function() {
  var HttpWrapperHelper, URL;

  URL = require('url-parse');

  module.exports = HttpWrapperHelper = (function() {
    function HttpWrapperHelper() {
      HttpWrapperHelper.__super__.constructor.call(this);
    }

    HttpWrapperHelper._makeParameters = function(params) {
      var property, query, value;
      if (params.length === 0) {
        '';
      }
      query = '?';
      for (property in params) {
        value = params[property];
        query += (encodeURIComponent(property)) + "=" + (encodeURIComponent(value)) + "&";
      }
      return query.slice(0, -1);
    };

    HttpWrapperHelper._getPath = function(resource, id, action, key) {
      if (key && id && action && id !== '' && action !== '') {
        return "/" + encodeURIComponent(resource) + "/" + encodeURIComponent(id) + "/" + encodeURIComponent(action) + "/" + encodeURIComponent(key);
      } else if (id && action && id !== '' && action !== '') {
        return "/" + encodeURIComponent(resource) + "/" + encodeURIComponent(id) + "/" + encodeURIComponent(action);
      } else if (id && id !== '') {
        return "/" + encodeURIComponent(resource) + "/" + encodeURIComponent(id);
      } else if (action && action !== '') {
        return "/" + encodeURIComponent(resource) + "/" + encodeURIComponent(action);
      }
      return "/" + encodeURIComponent(resource);
    };

    HttpWrapperHelper._parse = function(url) {
      return new URL(url);
    };

    return HttpWrapperHelper;

  })();

}).call(this);
