// Generated by CoffeeScript 1.9.3
(function() {
  var MojioAsyncAwaitStyle, MojioAuthSDK, MojioPromiseStyle, MojioReactiveStyle, MojioSDK, MojioSyncStyle, async, await, nock, should;

  should = require('should');

  MojioSDK = require('../../src/nodejs/sdk/MojioSDK');

  MojioAuthSDK = require('../../src/nodejs/sdk/MojioAuthSDK');

  MojioPromiseStyle = require('../../src/nodejs/styles/MojioPromiseStyle');

  MojioReactiveStyle = require('../../src/nodejs/styles/MojioReactiveStyle');

  MojioAsyncAwaitStyle = require('../../src/nodejs/styles/MojioAsyncAwaitStyle');

  MojioSyncStyle = require('../../src/nodejs/styles/MojioSyncStyle');

  nock = require('nock');

  async = require('asyncawait/async');

  await = require('asyncawait/await');

  describe('Node Mojio Auth SDK password type auth', function() {
    var authorization, call, testErrorResult, timeout;
    call = null;
    timeout = 50;
    authorization = {
      client_id: '5f81657f-47f6-4d86-8213-5c01c1f3a243',
      password: 'Test123!',
      response_type: 'password',
      username: 'testing'
    };
    beforeEach(function() {
      if (true || (process.env.FUNCTIONAL_TESTS != null)) {
        return timeout = 3000;
      } else {
        return call = nock('https://accounts.moj.io').post("/oauth2/token", authorization).reply(function(uri, requestBody, cb) {
          return cb(null, [
            200, {
              id: 1
            }
          ]);
        });
      }
    });
    testErrorResult = function(error, result) {
      (error === null).should.be["true"];
      return (result !== null).should.be["true"];
    };
    return it('can authorize with password flow, callback async', function(done) {
      var sdk;
      this.timeout(timeout);
      sdk = new MojioSDK({
        sdk: MojioAuthSDK,
        test: true
      });
      return sdk.token('5f81657f-47f6-4d86-8213-5c01c1f3a243', "fcca6c06-3d30-488e-947b-a6291e39ff3c").credentials('testing', 'Test123!').callback(function(error, result) {
        testErrorResult(error, result);
        if (call != null) {
          call.done();
        }
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=NodeAuthSDK_callback_test.js.map
