// Generated by CoffeeScript 1.10.0
(function() {
  sdk.get().vehicles("some id").history().locations("date range criteria");

  sdk.get().user("somebody in a query").vehicles().callback(function(error, result) {});

}).call(this);

//# sourceMappingURL=decode.js.map
