// Generated by CoffeeScript 1.9.3
(function() {
  var MojioRestSDK, MojioSDK, async, nock, should;

  MojioSDK = require('../../src/nodejs/sdk/MojioSDK');

  MojioRestSDK = require('../../src/nodejs/sdk/MojioRestSDK');

  should = require('should');

  async = require('async');

  nock = require('nock');

  describe('Node Mojio Fluent Rest SDK', function() {
    var authorization, call, callback_url, execute, mojio, sdk, setupNock, testErrorResult, timeout, user, vehicle;
    user = null;
    mojio = null;
    vehicle = null;
    call = null;
    timeout = 50;
    callback_url = "http://localhost:3000/callback";
    authorization = {
      client_id: 'id',
      client_secret: 'secret',
      redirect_uri: 'http://localhost:3000/callback',
      username: 'testing',
      password: 'Test123!',
      scope: 'full',
      grant_type: 'password'
    };
    sdk = new MojioSDK({
      sdk: MojioRestSDK,
      client_id: 'id',
      client_secret: 'secret',
      test: true
    });
    setupNock = function() {
      if ((process.env.FUNCTIONAL_TESTS != null)) {
        timeout = 3000;
        return {
          done: function() {}
        };
      } else {
        call = nock('https://staging-accounts.moj.io').post("/oauth2/token", authorization).reply(function(uri, requestBody, cb) {
          return cb(null, [
            200, {
              id: 1
            }
          ]);
        });
        return call;
      }
    };
    testErrorResult = function(error, result) {
      (error === null).should.be["true"];
      return (result !== null).should.be["true"];
    };
    execute = function(test, done) {
      return async.series([
        function(cb) {
          setupNock();
          return sdk.token(authorization.redirect_uri).credentials(authorization.username, authorization.password).scope(['full']).callback(function(error, result) {
            var token;
            if (error) {
              console.log('Access Token Error', JSON.stringify(error.content) + "  message:" + error.statusMessage + "  url:" + sdk.url());
            } else {
              token = result;
              console.log("Token:" + JSON.stringify(token));
            }
            return cb(error, result);
          });
        }, function(cb) {
          return sdk.mock().user({}).callback(function(error, result) {
            user = result;
            return cb(error, result);
          });
        }, function(cb) {
          return sdk.mojio({
            UserId: user.id,
            Imei: "9991234567891234"
          }).mock().callback(function(error, result) {
            mojio = result;
            return cb(error, result);
          });
        }, function(cb) {
          return sdk.mock().vehicle({
            MojioId: mojio.id,
            UserId: user.id,
            Speed: 80
          }).callback((function(error, result) {
            vehicle = result;
            return cb(error, result);
          }));
        }, function(cb) {
          return test(cb);
        }
      ], function(error, results) {
        if (error != null) {
          console.log(error);
        }
        (error === null).should.be["true"];
        (results !== null).should.be["true"];
        return done();
      });
    };
    beforeEach(function() {
      user = null;
      mojio = null;
      return vehicle = null;
    });
    it('can create create a vehicle', function(done) {
      this.timeout(5000);
      return execute(function(cb) {
        return sdk.create().vehicle({})["for"](user).callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
      }, done);
    });
    it('can create create a vehicle', function(done) {
      this.timeout(5000);
      return execute(function(cb) {
        return sdk.create().vehicle({})["for"](user).callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
      }, done);
    });
    it('can create share and revoke a vehicle', function(done) {
      this.timeout(5000);
      return execute(function(cb) {
        sdk.share().vehicle(vehicle)["with"](user).access("write").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
        return sdk.revoke().vehicle(vehicle).from(user).callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
      }, done);
    });
    it('can create share and revoke a list of vehicles', function(done) {
      this.timeout(5000);
      return execute(function(cb) {
        sdk.share().vehicles([vehicle])["with"](user).access("read").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
        return sdk.revoke().vehicles([vehicle]).from(user).access("read").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
      }, done);
    });
    it("can create share and revoke a vehicle's fields", function(done) {
      this.timeout(5000);
      return execute(function(cb) {
        sdk.share().vehicle(vehicle).fields(['location', 'speed'])["with"](user).access("read").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
        return sdk.revoke().vehicle(vehicle).from(user).access("read").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
      }, done);
    });
    return it('can create group add/remove users', function(done) {
      this.timeout(5000);
      return execute(function(cb) {
        sdk.create().group({
          name: "blah"
        })["with"]([user]).callback(function(error, result) {
          testErrorResult(error, result);
          return function(error, result) {
            var group;
            return group = result;
          };
        });
        sdk.group("blah").add(user).callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
        sdk.add(user).into().group("blah").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
        sdk.remove(user).outof().group("blah").callback(function(error, result) {
          testErrorResult(error, result);
          return cb(null, result);
        });
        return sdk.create().mojio({
          imei: "123981392131"
        });
      }, done);
    });
  });

}).call(this);

//# sourceMappingURL=NodeRestSDK_test.js.map
