// Generated by CoffeeScript 1.9.3
(function() {
  var Address, MojioModel,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MojioModel = require('./MojioModel');

  module.exports = Address = (function(superClass) {
    extend(Address, superClass);

    Address.prototype._schema = {
      "Address1": "String",
      "Address2": "String",
      "City": "String",
      "State": "String",
      "Zip": "String",
      "Country": "String"
    };

    Address.prototype._resource = 'Addresss';

    Address.prototype._model = 'Address';

    function Address(json) {
      Address.__super__.constructor.call(this, json);
    }

    Address._resource = 'Addresss';

    Address._model = 'Address';

    Address.resource = function() {
      return Address._resource;
    };

    Address.model = function() {
      return Address._model;
    };

    return Address;

  })(MojioModel);

}).call(this);

//# sourceMappingURL=Address.js.map
