// Generated by CoffeeScript 1.9.3
(function() {
  var MojioModel, ScriptObserver,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MojioModel = require('./MojioModel');

  module.exports = ScriptObserver = (function(superClass) {
    extend(ScriptObserver, superClass);

    ScriptObserver.prototype._schema = {
      "Script": "String",
      "Timing": "Integer",
      "Type": "Integer",
      "Name": "String",
      "ObserverType": "Integer",
      "AppId": "String",
      "OwnerId": "String",
      "Parent": "String",
      "ParentId": "String",
      "Subject": "String",
      "SubjectId": "String",
      "Transports": "Integer",
      "Status": "Integer",
      "Tokens": "Array",
      "_id": "String",
      "_deleted": "Boolean"
    };

    ScriptObserver.prototype._resource = 'ScriptObservers';

    ScriptObserver.prototype._model = 'ScriptObserver';

    function ScriptObserver(json) {
      ScriptObserver.__super__.constructor.call(this, json);
    }

    ScriptObserver._resource = 'ScriptObservers';

    ScriptObserver._model = 'ScriptObserver';

    ScriptObserver.resource = function() {
      return ScriptObserver._resource;
    };

    ScriptObserver.model = function() {
      return ScriptObserver._model;
    };

    return ScriptObserver;

  })(MojioModel);

}).call(this);

//# sourceMappingURL=ScriptObserver.js.map
